FROM oven/bun:latest as build

WORKDIR /app

COPY package.json ./
RUN bun install

COPY . .

EXPOSE 5173
# RUN bun run dev
CMD ["bun", "run", "dev", "--host"]


# FROM nginx:stable-alpine
# COPY --from=build /app/dist /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

