pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/AdityaAparadh/CICD.git'
            }
        }
        
        stage('Build Frontend') {
            steps {
                script {
                    sh 'docker build -t frontend-image -f Frontend/Dockerfile ./Frontend'
                }
            }
        }

        stage('Build Backend') {
            steps {
                script {
                    sh 'docker build -t backend-image -f Backend/Dockerfile ./Backend'
                }
            }
        }

        stage('Test Backend') {
            steps {
                script {
                    sh 'docker run --rm backend-image bun run test'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker compose up -d'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
